# Generated by Django 2.1 on 2019-01-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinGlassField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('site_num', models.IntegerField()),
                ('trotter_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=48)),
            ],
        ),
        migrations.AddField(
            model_name='spinglassfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.User'),
        ),
    ]
