# Generated by Django 2.1 on 2019-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinglassfield',
            name='user',
        ),
        migrations.AddField(
            model_name='spinglassfield',
            name='result',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spinglassfield',
            name='site_num',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='spinglassfield',
            name='trotter_num',
            field=models.IntegerField(default=10),
        ),
    ]
