# Generated by Django 2.1 on 2019-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20190126_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinglassfield',
            name='data',
            field=models.FileField(default=None, max_length=128, upload_to='data/'),
        ),
    ]
