# Generated by Django 2.1 on 2019-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_spinglassfield_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinglassfield',
            name='data',
            field=models.FileField(default='SG.dat', max_length=128, upload_to='data/'),
        ),
    ]
