# Generated by Django 2.1 on 2019-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20190128_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinglassfield',
            name='data',
            field=models.FileField(max_length=128, upload_to='data/'),
        ),
    ]
