# Generated by Django 2.1 on 2019-01-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20190128_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinglassfield',
            name='data',
        ),
    ]
