# Generated by Django 2.1 on 2019-01-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_remove_spinglassfield_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinglassfield',
            name='data',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='data/'),
        ),
    ]
