# Generated by Django 2.1 on 2019-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_spinglassfield_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinglassfield',
            name='data',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spinglassfield',
            name='name',
            field=models.CharField(max_length=48),
        ),
    ]
